run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/vijay-prabhu/jobsearch-mcp

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
